### ISSUE TITLE
Error: rportd.conf is a directory

### ISSUE THREAD

**Issue by LukasPoque** [MatthewReed303/rport-docker#1]
First of all, thank you for this docker template, this is exactly what I was looking for: a simple and easy-to-setup solution for RPort.

Sadly this isn't working out of the box for me :( I tried to start the container with docker-compose but the container log shows an error: `Invalid config: error reading config file: read /etc/rport/rportd.conf: is a directory`. Do I need to set up a folder structure before starting the container? Or what am I missing? 

regards

**Comment by MatthewReed303** [comment]
Hi @LukasPoque 

I see I have the readme wrong. Are you using my docker image?

https://hub.docker.com/r/mrea303/rport-docker

does your rportData directory contain: api-auth.json  client-auth.json  rport.crt  rportd.conf  rport.key

I will update it soon
